#!/bin/bash

if ! [ $(id -u) = 0 ]; then
    echo "run this in root"
exit 1
fi

echo "you will now change the usr passwords"

usr=usr

until[$usr == q]
do
    read -p "whats the username? q to stop: " usr
    echo newpw | sudo passwd $usr
done

read -p "do you want to remove users as well?[y/n]: " rem

if[[$rem == 'y']]; then{
    until[$usr == q]
do
    read -p "whats the username? q to stop: " usr
    userdel $usr
done
}

echo 'scripts all done...